---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: gcr.io/cloud-solutions-images/concourse-helm-gcp
    tag: v0.2.0

inputs:
- name: chart-source

outputs:
- name: helm-repo

params:
  chart_name: nginx
  bucket: ""

run:
  path: bash
  args:
  - -exc
  - |
    if [[ -z "$bucket" ]];then
      echo "Bucket name not set"
      exit 1
    fi
    mkdir -p helm-repo
    helm init --client-only
    GIT_SHA=$(cd chart-source && git rev-parse HEAD)
    APP_VERSION=$(cd chart-source && cat VERSION)
    VERSION="$APP_VERSION-$GIT_SHA"
    cp -a chart-source $chart_name
    helm package $chart_name -d helm-repo --version $VERSION
    helm gcs push helm-repo/$chart_name-$VERSION.tgz gs://$bucket
